project:
  type: website

website:
  title: "ISSS626-Geospatial-zytan"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 1a"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 1b"
          href: "Hands-on_Ex/Hands-on_Ex01b/Hands-on_Ex01b.html"
        - text: "Hands-on Exercise 2a"
          href: "Hands-on_Ex/Hands-on_Ex02a/Hands-on_Ex02a.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

